version: '3.1'

services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: simon
      MYSQL_PASSWORD: simon
    ports:
      - 3308:3306
    volumes:
      - db_data:/var/lib/mysql
 
  db2:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8081:80






volumes:
  db_data:
  pgdata:
   

